FROM node:14-alpine3.11
ARG SLACK_SIGNING_SECRET
ARG SLACK_BOT_TOKEN
ARG SLACK_APP_TOKEN
ARG OPENAI_API_KEY
WORKDIR /src

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY . .

RUN npm install




ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV PORT = 4000
ENV SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
EXPOSE 4000
CMD ["npm", "start"]